process.env.TEST_ENV = true
const FailRecord = require('../../../structs/db/FailRecord.js')

function getOldDate (hoursAgo) {
  // https://stackoverflow.com/questions/1050720/adding-hours-to-javascript-date-object
  const date = new Date()
  date.setTime(date.getTime() - hoursAgo * 60 * 60 * 1000)
  return date
}

describe('Unit::structs/db/FailRecord', function () {
  afterEach(function () {
    jest.restoreAllMocks()
  })
  describe('constructor', function () {
    it('initializes default values', function () {
      const data = {
        url: 'aesdgdf'
      }
      const record = new FailRecord(data)
      expect(record.failedAt).toBeDefined()
      expect(record.reason).toBeUndefined()
    })
    it('initializes with given values', function () {
      const data = {
        url: 'aesdgdf',
        reason: 'helaz'
      }
      const record = new FailRecord(data)
      expect(record.url).toEqual(data.url)
      expect(record.reason).toEqual(data.reason)
    })
  })
  describe('static record', function () {
    it('finds the right model', async function () {
      const spy = jest.spyOn(FailRecord, 'getBy').mockResolvedValue({
        save: jest.fn(),
        pastCutoff: jest.fn().mockReturnValue(false)
      })
      const url = 'srfyhed'
      await FailRecord.record(url)
      expect(spy).toHaveBeenCalledWith('url', url)
    })
    it('updates the reason the model if it exists', async function () {
      const reason = 'ewstr4ydh'
      const found = {
        save: jest.fn(),
        pastCutoff: jest.fn().mockReturnValue(false),
        reason: reason + 'abc'
      }
      jest.spyOn(FailRecord, 'getBy').mockResolvedValue(found)
      await FailRecord.record('', reason)
      expect(found.save).toHaveBeenCalledWith()
      expect(found.reason).toEqual(reason)
    })
    it('updates the alert the model if it exists', async function () {
      const reason = 'rrr'
      const found = {
        save: jest.fn(),
        reason,
        pastCutoff: jest.fn().mockReturnValue(true),
        alerted: false
      }
      jest.spyOn(FailRecord, 'getBy').mockResolvedValue(found)
      await FailRecord.record('', reason)
      expect(found.save).toHaveBeenCalledWith()
      expect(found.alerted).toEqual(true)
    })
    it('returns the record if it exists', async function () {
      const reason = 'rrr'
      const found = {
        save: jest.fn(),
        pastCutoff: jest.fn().mockReturnValue(false),
        reason,
        alerted: true
      }
      jest.spyOn(FailRecord, 'getBy').mockResolvedValue(found)
      const returned = await FailRecord.record('', reason)
      expect(returned).toEqual(found)
    })
    it('sends fail message if failed and not alerted', async function () {
      const reason = 'rrr'
      const found = {
        save: jest.fn(),
        reason,
        pastCutoff: jest.fn().mockReturnValue(true),
        alerted: false
      }
      jest.spyOn(FailRecord, 'getBy').mockResolvedValue(found)
      const spy = jest.spyOn(FailRecord, 'sendFailMessage').mockReturnValue()
      await FailRecord.record('', reason)
      expect(spy).toHaveBeenCalled()
    })
  })
  describe('static reset', function () {
    it('finds the right model', async function () {
      const spy = jest.spyOn(FailRecord, 'getBy').mockResolvedValue({
        delete: jest.fn()
      })
      const url = 'srfyhed'
      await FailRecord.reset(url)
      expect(spy).toHaveBeenCalledWith('url', url)
    })
    it('deletes the found model', async function () {
      const found = {
        delete: jest.fn()
      }
      jest.spyOn(FailRecord, 'getBy').mockResolvedValue(found)
      const url = 'srfyhed'
      await FailRecord.reset(url)
      expect(found.delete).toHaveBeenCalled()
    })
  })
  describe('static hasFailed', function () {
    it('returns false if getBy returns null', async function () {
      jest.spyOn(FailRecord, 'getBy').mockResolvedValue(null)
      const returned = await FailRecord.hasFailed()
      expect(returned).toEqual(false)
    })
    it('return the value of protoype.hasFailed if found', async function () {
      const hasFailed = jest.fn(() => true)
      const found = {
        hasFailed
      }
      jest.spyOn(FailRecord, 'getBy').mockResolvedValue(found)
      await expect(FailRecord.hasFailed())
        .resolves.toEqual(true)
      hasFailed.mockReturnValue(false)
      await expect(FailRecord.hasFailed())
        .resolves.toEqual(false)
    })
  })
  describe('pastCutoff', function () {
    const cutoff = 2
    const oldDate = getOldDate(cutoff + 1)
    const atDate = getOldDate(cutoff)
    const recentDate = getOldDate(cutoff - 1)
    beforeEach(function () {
      jest.spyOn(FailRecord, 'cutoff', 'get').mockReturnValue(cutoff)
    })
    it('returns false if cutoff is 0', function () {
      jest.spyOn(FailRecord, 'cutoff', 'get').mockReturnValue(0)
      const data = {
        url: 'sg'
      }
      const record = new FailRecord(data)
      expect(record.pastCutoff()).toEqual(false)
    })
    it('returns false if failedAt is recent', function () {
      const data = {
        url: 'sg'
      }
      const record = new FailRecord(data)
      record.failedAt = recentDate.toISOString()
      expect(record.pastCutoff()).toEqual(false)
    })
    it('returns true if count at or above limit', function () {
      const data = {
        url: 'sg'
      }
      const record = new FailRecord(data)
      record.failedAt = atDate.toISOString()
      expect(record.pastCutoff()).toEqual(true)
      record.failedAt = oldDate.toISOString()
      expect(record.pastCutoff()).toEqual(true)
    })
  })
  describe('hasFailed', function () {
    it('returns pastCutoff func value', function () {
      const data = {
        url: 'wseg'
      }
      const record = new FailRecord(data)
      const pastCutoff = 32546
      jest.spyOn(record, 'pastCutoff').mockReturnValue(pastCutoff)
      const returned = record.hasFailed()
      expect(returned).toEqual(pastCutoff)
    })
  })
  describe('toObject', function () {
    it('returns correctly', function () {
      const data = {
        url: 'aetgswr'
      }
      const record = new FailRecord(data)
      const url = 'w49y6huie'
      const reason = 'jackzzz'
      const failedAt = 'q3w24t6ery5tu6'
      const alerted = true
      record.url = url
      record.reason = reason
      record.failedAt = failedAt
      record.alerted = alerted
      const returned = record.toObject()
      expect(returned).toEqual({
        url,
        reason,
        failedAt,
        alerted
      })
    })
  })
})
